declare module '@env' {
  export const VERVE_SEARCH_API_KEY: string;
  export const FLUTTERWAVE_PUBLIC_KEY: string;
  export const WEB_CLIENT_ID: string;
  export const WEB_CLIENT_SECRET: string;
  export const GITHUB_CLIENT_ID: string;
  export const GITHUB_CLIENT_SECRET: string;
  export const GEMINI_API_KEY: string;
  export const SERVICE_UUID: string;
  export const EXCHANGERATE_API_KEY: string;
  export const ICAMPUS_APPLE_ID: string;
  export const APIKEY: string;
  export const AUTH_DOMAIN: string;
  export const PROJECT_ID: string;
  export const STORAGE_BUCKET: string;
  export const MESSAGING_SENDER_ID: string;
  export const APP_ID: string;
  export const MEASUREMENT_ID: string
}
